paths:
  raw_dir: /opt/airflow/data/raw
  parquet_dir: /opt/airflow/data/parquet
  cleaned_dir: /opt/airflow/data/cleaned

preprocessing:
  constant_properties:
    - "159"
    - "112"
    - "764"

  parquet_compression: SNAPPY

s3:
  endpoint_url: https://storage.yandexcloud.net
  data_prefix: recsys/data

  files:
    events: events.parquet
    item_properties: item_properties.parquet
    category_tree: category_tree.parquet

airflow:
  owner: mle-user
  retries: 2
  retry_delay_minutes: 2